-- Optional production migration plan for high-volume installs.
-- Do not run blindly on an existing production table without a maintenance window.
-- Prisma does not model PostgreSQL partitioning directly, so this stays manual.

-- Target shape:
--   "ServerHistory" partitioned by RANGE (timestamp)
--   one partition per month
--   retention cleanup via DROP TABLE old_partition instead of DELETE

-- Sketch for a new replacement table:
-- CREATE TABLE "ServerHistory_partitioned" (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--   server_id TEXT NOT NULL,
--   clients INTEGER NOT NULL,
--   timestamp TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   CONSTRAINT "ServerHistory_partitioned_pkey" PRIMARY KEY (id, timestamp),
--   CONSTRAINT "FK_server_history_servers_partitioned"
--     FOREIGN KEY (server_id)
--     REFERENCES "Server"(id)
--     ON DELETE CASCADE
--     ON UPDATE CASCADE
-- ) PARTITION BY RANGE (timestamp);

-- Example monthly partition:
-- CREATE TABLE "ServerHistory_2026_05"
-- PARTITION OF "ServerHistory_partitioned"
-- FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
--
-- CREATE INDEX "ServerHistory_2026_05_server_id_timestamp_idx"
-- ON "ServerHistory_2026_05" (server_id, timestamp DESC);
--
-- CREATE INDEX "ServerHistory_2026_05_timestamp_idx"
-- ON "ServerHistory_2026_05" (timestamp);

-- After backfilling and validating row counts, swap names in a maintenance window:
-- ALTER TABLE "ServerHistory" RENAME TO "ServerHistory_old";
-- ALTER TABLE "ServerHistory_partitioned" RENAME TO "ServerHistory";

-- Retention then becomes cheap:
-- DROP TABLE IF EXISTS "ServerHistory_2026_03";
